version: "1.27.0"
services:
  mongodb:
    container_name: mongo-db
    image: mongo
    volumes:
      - mongodbdata:/data/db
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=admin
    #  - MONGO_INITDB_ROOT_PASSWORD=password
    env_file:
      - ./env/mongo.env
  backend:
    container_name: todo-backend-app
    build:
      context: ./backend
      #dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    container_name: todo-frontend-app
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  mongodbdata: